export const languages = [
  { id: "af", name: "Afrikaans" },
  { id: "ar", name: "Arabic" },
  { id: "zh", name: "Chinese" },
  { id: "da", name: "Danish" },
  { id: "en", name: "English" },
  { id: "fr", name: "French" },
  { id: "de", name: "German" },
  { id: "el", name: "Greek" },
  { id: "it", name: "Italian" },
  { id: "hi", name: "Indian" },
  { id: "id", name: "Indonesian" },
  { id: "ja", name: "Japan" },
  { id: "ko", name: "Korean" },
  { id: "no", name: "Norwegian" },
  { id: "pl", name: "Polish" },
  { id: "pt", name: "Portuguese" },
  { id: "ru", name: "Russian" },
  { id: "es", name: "Spanish" },
  { id: "sv", name: "Swedish" },
  { id: "ta", name: "Tamil" },
  { id: "th", name: "Thai" },
  { id: "tr", name: "Turkish" },
  { id: "vi", name: "Vietnamese" },
];
